### ISSUE TITLE
TargetFramwork does not align with autofac

### ISSUE THREAD

**Issue by Aniel** [autofac/Autofac.Mef#16]
The target framework in version `4.1.0` is not compatible with .NET 4.7.2. 

>`Package Autofac.Mef 4.1.0 is not compatible with net472 (.NETFramework,Version=v4.7.2) / win. Package Autofac.Mef 4.1.0 supports: netstandard2.0 (.NETStandard,Version=v2.0)`

The Autofac project has its TargetFramwork property set to `netstandard2.1;netstandard2.0;net461` [source](https://github.com/autofac/Autofac/blob/c247e60ce8c9cb1545384e763e41798b3998ee59/src/Autofac/Autofac.csproj#L6)  
I propose aligning the TargetFramwork of `Autofac.Mef` with the TargetFramwork from `Autofac`.

Should I open a PR for this?

**Comment by tillig** [comment]
.NET Framework 4.6.1 and above is [compatible with `netstandard2.0`](https://docs.microsoft.com/en-us/dotnet/standard/net-standard). There shouldn't need to be any change if it's being used from .NET 4.7.2. My guess is something else is going on here, like perhaps an old version of NuGet that doesn't understand the netstandard stuff.

Can we see a repro project?

**Comment by Aniel** [comment]
After checking with the IT department I discovered that our freshly (2 weeks ago) created build server has `nuget 4.1` installed 🙈 It seems they forgot to install the latest tools and just reused an old copy they had on their file share...

The issue is therefore resolved. Thank you for the pointer in the right direction 👌
