### ISSUE TITLE
How to export an existing registration

### ISSUE THREAD

**Issue by dazinator** [autofac/Autofac.Mef#6]
I am using this in an ASP.NET 5 application, where I populate a container builder with existing ASP.NET services from an `IServiceCollecton`

```
var bootstrapApplicationContainerBuilder = new ContainerBuilder();
bootstrapApplicationContainerBuilder.Populate(services);
```

I am aware that I can add new registrations for Export like this:

```

 bootstrapApplicationContainerBuilder.RegisterInstance(config).As<IConfiguration>()
                                                            .Exported(x => x.As<IConfiguration>()); // allow
```

But, how do I export an existing Registration - for a service thats been added via "PopulateServices()" ?

**Comment by tillig** [comment]
Short answer is "you can't." Sorry. The `Populate` method is what iterates through the service collection and registers things directly into the container builder. There's no opportunity to "intercept" these registrations to add functionality to them.
